version: "3.8"

services:
  backend:
    build:
        context: .
        dockerfile: ./dockerfiles.backend
    container_name: backend
    ports:
        - "5000:5000"
    volumes:
        - ./backend:/app
    environment:
        - FLASK_ENV=development
